image: 'maven:alpine'

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.war
      - target/*-thorntail.jar
    expire_in: 1 week

test:
  stage: test
  script:
    - mvn test

after_script:
  - echo "End CI"
